
about:
  name: Orchid Materialize Theme
  description: A theme for Orchid using Materialize CSS.

github:
  username: 'JavaEden'
  repo: 'Orchid'
  branch: 'master'

generators:
  disabled:
    - 'JavadocClassesGenerator'
    - 'JavadocPackagesGenerator'
    - 'ChangelogGenerator'
    - 'PostsGenerator'