language: java
dist: trusty
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - master
    - dev

jobs:
  include:
    - os: linux
      jdk: openjdk8
      install: ./gradlew assemble -PnoJavadoc=true
      script: ./gradlew check
    - os: linux
      jdk: oraclejdk8
      install: ./gradlew assemble -PnoJavadoc=true
      script: ./gradlew check
    - os: osx
      osx_image: xcode8.3
      install: ./gradlew assemble -PnoJavadoc=true
      script: ./gradlew check

    - stage: upload test results
      os: linux
      jdk: openjdk8
      install: ./gradlew assemble
      script: ./gradlew check
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: release
      os: linux
      jdk: openjdk8
      install: ./gradlew assemble -Penv=prod -Prelease
      script: ./gradlew deploy -Penv=prod -Prelease
      after_success:
        - git config --local user.name "Travis CI Deployment Bot"
        - git config --local user.email "deploy@travis-ci.org"
        - ./gradlew tag -Prelease
      deploy:
        - provider: releases
          skip_cleanup: true
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: ${TRAVIS_BUILD_DIR}/build/orchid/archives/*
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ${TRAVIS_BUILD_DIR}/build/orchid/docs
          target_branch: pages

stages:
  - test
  - upload test results
  - name: release
    if: branch = master AND tag IS blank
