language: java
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode8.3
dist: trusty
sudo: required

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: release.sh
    on:
      branch: master