language: java
dist: trusty
sudo: required

jobs:
  include:
    - os: linux
      jdk: openjdk8
      install: ./gradlew assemble
      script: ./gradlew check
    - os: linux
      jdk: oraclejdk8
      install: ./gradlew assemble
      script: ./gradlew check
    - os: osx
      osx_image: xcode8.3
      install: ./gradlew assemble
      script: ./gradlew check

    - stage: upload test results
      script: bash <(curl -s https://codecov.io/bash)

    - stage: release
      os: linux
      jdk: openjdk8
      script: ./gradlew clean build deploy -Penv=prod -Prelease -PskipMavenCentralSync=true

stages:
  - test
  - upload test results
  - name: release
    if: branch = master