
theme:
  about:
    siteName: OrchidCore
    siteDescription: A beautiful and truly unique documentation engine and static site generator.
  social:
    github: 'JavaEden/Orchid'
  primaryColor: '#ffa033'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'wikiSections'
    - type: 'pages'
      section: 'plugins'
    - type: 'pages'
      section: 'themes'
    - type: 'pages'
      section: 'bundles'
    - type: 'postCategories'
      title: 'News'
    - type: 'javadocPackages'
    - type: 'javadocClasses'

wiki:
  layout: 'wikiPage'
  includeIndexInPageTitle: true
  sections:
    - 'userManual'
    - 'developersGuide'

services:
  generators:
    disabled:
      - 'presentations'
      - 'styleguide'

allPages:
  components:
    - type: pageContent
      order: 10
    - type: prism
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'groovy'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'

wikiPages:
  layout: geopattern2