
theme:
  about:
    siteName: OrchidCore
    siteDescription: A beautiful and truly unique documentation engine and static site generator.
  social:
    github: 'JavaEden/Orchid'
  primaryColor: '#ffa033'
  commonPageElements:
    - type: prism
      theme: 'twilight'
      languages:
        - 'yaml'
        - 'java'
        - 'groovy'
        - 'markdown'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'wikiSections'
    - type: 'pages'
      section: 'plugins'
    - type: 'pages'
      section: 'themes'
    - type: 'pages'
      section: 'bundles'
    - type: 'postCategories'
      title: 'News'
    - type: 'javadocPackages'
    - type: 'javadocClasses'
  extraCss:
    - 'https://rawgit.com/PrismJS/prism-themes/master/themes/prism-darcula.css'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/line-numbers/prism-line-numbers.min.css'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/line-highlight/prism-line-highlight.min.css'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/toolbar/prism-toolbar.min.css'
  extraJs:
    - 'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/prism.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/line-numbers/prism-line-numbers.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/line-highlight/prism-line-highlight.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/toolbar/prism-toolbar.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/show-language/prism-show-language.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/components/prism-java.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/components/prism-yaml.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/components/prism-markdown.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.4/components/prism-groovy.min.js'

wiki:
  layout: 'wikiPage'
  sections:
    - 'userManual'
    - 'developersGuide'

services:
  generators:
    disabled:
      - 'presentations'
      - 'styleguide'

wikiPages:
  layout: geopattern2