
about:
  name: Orchid Liquid
  description: A modern Javadoc-generation doclet based on Liquid, Sass, Markdown, and YAML
  version: v0.1.0

colors:
  - '#FF8800'
  - '#000000'

github:
  username: 'JavaEden'
  repo: 'Orchid-Liquid'
  branch: 'master'