BsDoc:
  about:
    siteName: 'Bootstrap Docs'
    description: 'Detrius, caesium, et mineralis?'
    githubUsername: 'JavaEden'
    githubRepo: 'Orchid'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'postCategories'
      title: 'Blog'
    - type: 'page'
      page: 'Resume'
    - type: 'page'
      page: 'Projects'
    - type: 'page'
      page: 'Bio'
    - type: 'page'
      page: 'Contact'

pages:
  layout: layouts/geopattern2.twig

posts:
  layout: layouts/index2.twig
  categories:
    - 'personal'
    - 'programming'
  permalink: ':category/:year/:monthName/:slug'
  authors:
    - name: 'Casey Brooks'
      avatar: 'assets/images/avatar.jpg'

generators:
  disabled:
    - 'WikiGenerator'
    - 'IndexGenerator'
    - 'JavadocGenerator'
    - 'ChangelogGenerator'
    - 'KssGenerator'
