
about:
  name: Orchid Diagrams
  description: Convert PlantUML diagrams into embeddable SVGs.

#colors:
#  primary: 'light-green'
#  secondary: 'orange'
#
colors:
  primary: '#8BC34A'
  secondary: '#000000'

shades:
  primary: 'base'

navigation:
  headerBackground: 'https://s-media-cache-ak0.pinimg.com/736x/a0/d5/29/a0d529fdfe67a8905e57d8c4967b0758.jpg'

github:
  username: 'JavaEden'
  repo: 'Orchid'
  branch: 'master'
