
about:
  name: Orchid Editorial Theme
  description: A beautiful theme for Orchid created by HTML5 UP.

github:
  username: 'JavaEden'
  repo: 'Orchid'
  branch: 'master'

colors:
  - #4C376C
  - #000000