
about:
  name: OrchidCore
  description: A modern, extensible, theme-ready Javadoc site generator.

colors:
  primary: 'grey'
  secondary: 'orange'

shades:
  primary: 'darken-2'

github:
  username: 'JavaEden'
  repo: 'Orchid'
  branch: 'master'

posts:
  permalink: ':year/:month/:title'
  categories:
    - 'personal'
    - 'development'