
wiki:
  layout: 'wikiPage'
  sections:
    - 'userManual'
    - 'developersGuide'

services:
  generators:
    disabled:
      - 'javadoc'
      - 'pages'
      - 'presentations'
      - 'styleguide'