
about:
  name: Orchid
  description: A modern, plugin-driven architecture for custom Javadoc generation

colors:
  - '#FF8800'
  - '#000000'

github:
  username: 'JavaEden'
  repo: 'OrchidCore'
  branch: 'master'
