
about:
  name: Orchid BSDoc Theme
  description: A theme for Orchid based off the Bootstrap documentation site.

github:
  username: 'JavaEden'
  repo: 'Orchid'
  branch: 'master'

disabledGenerators:
#  - 'AssetsGenerator'
  - 'JavadocClassesGenerator'
#  - 'PagesGenerator'
#  - 'PostsGenerator'
#  - 'WikiGenerator'
  - 'JavadocPackagesGenerator'
#  - 'HomepageGenerator'
  - 'IndexGenerator'