
about:
  name: Orchid Editorial Theme
  description: A beautiful theme for Orchid created by HTML5 UP.

github:
  username: 'JavaEden'
  repo: 'Orchid'
  branch: 'master'

disabledGenerators:
#  - 'AssetsGenerator'
  - 'JavadocClassesGenerator'
#  - 'PagesGenerator'
#  - 'PostsGenerator'
#  - 'WikiGenerator'
  - 'JavadocPackagesGenerator'
#  - 'HomepageGenerator'
  - 'IndexGenerator'